# EverWrapMCP remote connector image. Contains code and public model files only:
# no policy, passphrase, encryption key or Evernote credentials. Those are mounted
# at runtime (see deploy/compose.yaml and docs/REMOTE.md).

ARG PYTHON_IMAGE=python:3.12-slim-bookworm@sha256:392307d22300de8b5986851a12d9176dfc0fc073e65bf6523ebd7dcbeb23564e
FROM ghcr.io/astral-sh/uv:0.11.2@sha256:c4f5de312ee66d46810635ffc5df34a1973ba753e7241ce3a08ef979ddd7bea5 AS uv

FROM ${PYTHON_IMAGE} AS build
COPY --from=uv /uv /usr/local/bin/uv
ENV HOME=/home/everwrap UV_LINK_MODE=copy UV_NO_CACHE=1
WORKDIR /app
# Every package is hash-pinned (deploy/requirements-image.txt, regenerated by
# deploy/lock-image-requirements.sh). The lock resolves CUDA torch on Linux, so the
# same torch version is installed as the CPU-only wheel, also by pinned hash.
COPY deploy/requirements-image.txt ./
RUN set -eu; \
    uv venv /opt/venv; \
    echo "torch @ https://download-r2.pytorch.org/whl/cpu/torch-2.14.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl --hash=sha256:a09987c95ec4cffdb6df798d3d641558110a334cfccce22f2f046d83142bc260" > /tmp/torch.txt; \
    uv pip install --python /opt/venv/bin/python --require-hashes --no-deps -r /tmp/torch.txt; \
    # requirements-live.txt deliberately raises cryptography above presidio's cap
    # (docs/DEPENDENCY_SECURITY.md). The compiled file records the result but not the
    # override, so pass the same hashed cryptography entry as an override again.
    awk '/^cryptography==/{p=1} p{print} p&&!/\\$/{exit}' requirements-image.txt > /tmp/override.txt; \
    grep -q '^cryptography==' /tmp/override.txt; \
    uv pip install --python /opt/venv/bin/python --require-hashes \
      --override /tmp/override.txt -r requirements-image.txt
COPY src ./src
# Pinned public Turkish NER weights (skipped when the tr extra is not built).
RUN if /opt/venv/bin/python -c "import transformers" 2>/dev/null; then \
      PYTHONPATH=src /opt/venv/bin/python -m everwrap.language; fi; \
    mkdir -p /home/everwrap/.cache

FROM ${PYTHON_IMAGE}
RUN useradd --uid 10001 --home-dir /home/everwrap --shell /usr/sbin/nologin everwrap \
    && mkdir -p /data /config && chown 10001:10001 /data
COPY --from=build /opt/venv /opt/venv
COPY --from=build --chown=10001:10001 /home/everwrap/.cache /home/everwrap/.cache
COPY --from=build /app/src /app/src
ENV PATH=/opt/venv/bin:$PATH PYTHONPATH=/app/src HOME=/home/everwrap \
    PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 \
    HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 HF_HUB_DISABLE_TELEMETRY=1 \
    XDG_CACHE_HOME=/tmp/cache \
    EVERWRAP_POLICY=/config/policy.json EVERWRAP_DATA_DIR=/data \
    EVERWRAP_CREDENTIAL_KEY_FILE=/run/secrets/credential_key \
    EVERWRAP_PASSPHRASE_HASH_FILE=/run/secrets/passphrase_hash \
    EVERWRAP_CALLBACK_HOST=0.0.0.0 EVERWRAP_PORT=8000
WORKDIR /app
USER 10001
EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=5s --start-period=180s --retries=3 \
  CMD ["python", "-c", "import urllib.request,sys; sys.exit(urllib.request.urlopen('http://127.0.0.1:8000/healthz', timeout=4).read() != b'ok')"]
CMD ["python", "-m", "everwrap.remote", "serve"]
